name: Build and Deploy ðŸš€
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
      - run: |
          java HalloWelt.java
          
      - run: |
          chmod +x render.sh
          ./render.sh
        working-directory: documentation
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "documentation/public/*.svg"
          overwrite: true
          verbose: true
          update_latest_release: true 
